# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a9088bb0050d54506d5fc2adfb41f501f1f7ef4328e4c6db006ecb66221d4060897811ef803d0223c2b4f1cc07661d4af3060393d5308aeee749d4832f9e15f

test:
  secret_key_base: de89da8ba06c2d4cdcc489a1fb89e30d379094a62dd87a5ab18279cd0656420fcd67d0cc83044f8a614be54f71bab60ab0dd341fc157a6e1d56c49c5f2cda875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
